<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>library</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnableHarmony>true</EnableHarmony>
    </PropertyGroup>

  <PropertyGroup>
    <GamePath>E:\SteamLibrary\steamapps\common\Stardew Valley</GamePath>
  </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="JetBrains.Annotations" Version="2025.2.0" />
      <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.3.2" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="PythonApp\StardewSpriteTokens.build\**" />
      <Compile Remove="PythonApp\StardewSpriteTokens.onefile-build\**" />
      <Compile Remove="PythonApp\StardewSpriteTokens.dist\**" />
      <Compile Remove="PythonApp\StardewSpriteTokens\**" />
      <Compile Remove="PythonApp\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="PythonApp\StardewSpriteTokens.build\**" />
      <EmbeddedResource Remove="PythonApp\StardewSpriteTokens.onefile-build\**" />
      <EmbeddedResource Remove="PythonApp\StardewSpriteTokens.dist\**" />
      <EmbeddedResource Remove="PythonApp\StardewSpriteTokens\**" />
      <EmbeddedResource Remove="PythonApp\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="PythonApp\StardewSpriteTokens.build\**" />
      <None Remove="PythonApp\icon.ico" />
      <None Remove="PythonApp\StardewSpriteTokens.onefile-build\**" />
      <None Remove="PythonApp\StardewSpriteTokens.dist\**" />
      <None Remove="PythonApp\StardewSpriteTokens.exe" />
      <None Remove="PythonApp\StardewSpriteTokens\**" />
      <None Remove="PythonApp\flutter_sprite_editor\.gitignore" />
      <None Remove="PythonApp\flutter_sprite_editor\windows\flutter\ephemeral\cpp_client_wrapper\binary_messenger_impl.h" />
      <None Remove="PythonApp\flutter_sprite_editor\windows\flutter\ephemeral\cpp_client_wrapper\byte_buffer_streams.h" />
      <None Remove="PythonApp\flutter_sprite_editor\windows\flutter\ephemeral\cpp_client_wrapper\include\flutter\event_channel.h" />
      <None Remove="PythonApp\flutter_sprite_editor\windows\flutter\ephemeral\cpp_client_wrapper\include\flutter\method_codec.h" />
      <None Remove="PythonApp\flutter_sprite_editor\windows\flutter\ephemeral\cpp_client_wrapper\include\flutter\method_call.h" />
      <None Remove="PythonApp\flutter_sprite_editor\windows\runner\Runner.rc" />
      <None Remove="PythonApp\flutter_sprite_editor\build\.last_build_id" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\CMakeFiles\3.31.6-msvc6\CompilerIdCXX\Debug\CompilerIdCXX.tlog\CL.write.1.tlog" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\CMakeFiles\3.31.6-msvc6\CompilerIdCXX\Debug\CompilerIdCXX.tlog\CL.read.1.tlog" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\plugins\screen_retriever_windows\screen_retriever_windows_plugin.dir\Debug\screen_retriever_windows_plugin.ilk" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\plugins\screen_retriever_windows\screen_retriever_windows_plugin.dir\Debug\screen_r.E888F5C8.tlog\screen_retriever_windows_plugin.lastbuildstate" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\plugins\screen_retriever_windows\screen_retriever_windows_plugin.dir\Debug\screen_r.E888F5C8.tlog\CL.command.1.tlog" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\plugins\screen_retriever_windows\screen_retriever_windows_plugin.dir\Debug\screen_r.E888F5C8.tlog\link.read.1.tlog" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\plugins\screen_retriever_windows\screen_retriever_windows_plugin.dir\Debug\screen_r.E888F5C8.tlog\CL.read.1.tlog" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\plugins\file_selector_windows\file_selector_windows_plugin.vcxproj.filters" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\plugins\file_selector_windows\file_selector_windows_plugin.dir\Debug\file_selector_windows_plugin.dll.recipe" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\plugins\file_selector_windows\file_selector_windows_plugin.dir\Debug\file_selector_windows_plugin.ilk" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\plugins\file_selector_windows\file_selector_windows_plugin.dir\Debug\file_dialog_controller.obj" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\plugins\file_selector_windows\cmake_install.cmake" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\plugins\window_manager\window_manager_plugin.dir\Debug\window_manager_plugin.dll.recipe" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\plugins\window_manager\window_manager_plugin.dir\Debug\window_manager_plugin.obj" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\plugins\window_manager\window_manager_plugin.dir\Debug\window_m.3C49741E.tlog\link.secondary.1.tlog" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\plugins\window_manager\ALL_BUILD.vcxproj.filters" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\plugins\window_manager\INSTALL.vcxproj.filters" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\plugins\window_manager\Debug\window_manager_plugin.pdb" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\plugins\window_manager\Debug\window_manager_plugin.lib" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\plugins\window_manager\Debug\window_manager_plugin.exp" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\flutter\flutter_assemble.vcxproj.filters" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\flutter\flutter_wrapper_plugin.dir\Debug\flutter_.E47E6D50.tlog\Lib.command.1.tlog" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\flutter\flutter_wrapper_plugin.dir\Debug\flutter_.E47E6D50.tlog\CL.command.1.tlog" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\flutter\flutter_wrapper_app.dir\Debug\flutter_.614712FF.tlog\CustomBuild.read.1.tlog" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\flutter\flutter_wrapper_app.dir\Debug\flutter_.614712FF.tlog\Lib.command.1.tlog" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\runner\flutter_sprite_editor.dir\Debug\flutter_.C026B0DC.tlog\rc.command.1.tlog" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\runner\flutter_sprite_editor.dir\Debug\flutter_.C026B0DC.tlog\link.write.1.tlog" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\runner\flutter_sprite_editor.dir\Debug\flutter_.C026B0DC.tlog\rc.read.1.tlog" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\runner\flutter_sprite_editor.dir\Debug\utils.obj" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\runner\Debug\window_manager_plugin.dll" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\runner\Debug\flutter_sprite_editor.pdb" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\CustomBuild.command.1.tlog" />
      <None Remove="PythonApp\flutter_sprite_editor\build\windows\x64\x64\Debug\ALL_BUILD\ALL_BUILD.tlog\ALL_BUILD.lastbuildstate" />
      <None Remove="PythonApp\**" />
    </ItemGroup>

</Project>
